from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import streamlit as st


ROOT = Path(__file__).resolve().parents[1]
WORKFLOW_DIR = ROOT / "outputs" / "workflow"
TABLES_DIR = ROOT / "outputs" / "tables"
DATA_DIR = ROOT / "data"


st.set_page_config(page_title="Background & Methods", layout="wide")
st.title("SEC Comment Letter Evaluation: A Step-by-Step Guide")
st.caption("A transparent walkthrough from source data to event-study and regression outputs.")


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def read_table(csv_path: Path, parquet_path: Path | None = None, **kwargs) -> pd.DataFrame:
    if parquet_path is not None and parquet_path.exists():
        return pd.read_parquet(parquet_path)
    return pd.read_csv(csv_path, **kwargs)


tabs = st.tabs(
    [
        "(1) Overview",
        "(2) S&P 500 Reference",
        "(3) SEC Raw Download",
        "(4) Filing to Thread",
        "(5) Event Dataset",
        "(6) Text Features",
        "(7) Market Data",
        "(8) Event Study & Regression",
        "(9) Full Code Example",
    ]
)


with tabs[0]:
    st.header("Overview")
    st.write(
        "This page documents the project workflow. Each tab explains one stage, shows the key "
        "processing logic, and displays a real preview table generated by the pipeline."
    )
    st.markdown(
        """
The project follows this sequence:

1. Build the S&P 500 reference universe.
2. Download and preserve SEC correspondence artifacts.
3. Convert individual filings into comment-letter threads.
4. Convert threads into event-level observations.
5. Extract text features, topic labels, and severity scores.
6. Link events to market data.
7. Estimate event-study windows and regression outputs.

For each step, human-readable CSV/JSON files are kept for validation, while Parquet files are used as efficient pandas/Streamlit data caches when available.
"""
    )


with tabs[1]:
    summary_path = WORKFLOW_DIR / "01_sp500_reference_summary.json"
    preview_path = WORKFLOW_DIR / "01_sp500_reference_preview.csv"
    sector_path = TABLES_DIR / "sp500_sector_summary.csv"
    full_csv_path = DATA_DIR / "raw" / "reference" / "sp500_constituents.csv"
    full_parquet_path = DATA_DIR / "raw" / "reference" / "sp500_constituents.parquet"

    st.header("S&P 500 Reference Data")
    st.write("This step creates the firm universe reference table used by later sampling and SEC matching steps.")

    if not summary_path.exists():
        st.warning("Step 1 artifacts are not available yet. Run `./.venv/bin/python run.py --step sp500`.")
    else:
        summary = load_json(summary_path)
        metrics = summary["metrics"]
        cols = st.columns(4)
        cols[0].metric("Companies", metrics["company_count"])
        cols[1].metric("Sectors", metrics["sector_count"])
        cols[2].metric("Unique tickers", metrics["unique_ticker_count"])
        cols[3].metric("Source", summary["source"])

        st.subheader("Processing Logic")
        st.markdown(
            """
- Read the S&P 500 constituents table.
- Normalize ticker symbols, CIK values, sector fields, and source metadata.
- Save canonical CSV and Parquet copies.
- Export preview and sector summary tables for presentation.
"""
        )

        st.subheader("Output Files")
        st.dataframe(pd.DataFrame({"file": summary["output_files"]}), use_container_width=True)

        st.subheader("Reference Data Preview")
        st.write("This preview is a small CSV export meant for human inspection.")
        st.dataframe(pd.read_csv(preview_path, dtype={"cik": str}), use_container_width=True)

        st.subheader("Sector Summary")
        st.dataframe(pd.read_csv(sector_path), use_container_width=True)

        with st.expander("Full reference table loaded by pandas"):
            st.write("Streamlit loads the Parquet cache when available, with CSV as the human-readable companion.")
            st.dataframe(
                read_table(full_csv_path, full_parquet_path, dtype={"cik": str}),
                use_container_width=True,
            )

        with st.expander("QA notes"):
            for note in summary["notes"]:
                st.write(f"- {note}")


with tabs[2]:
    summary_path = WORKFLOW_DIR / "02_sec_raw_summary.json"
    preview_path = WORKFLOW_DIR / "02_sec_raw_preview.csv"
    thread_inventory_path = WORKFLOW_DIR / "02_sec_thread_inventory.csv"
    form_summary_path = TABLES_DIR / "sec_raw_form_summary.csv"

    st.header("SEC Raw Cache Inventory")
    st.write(
        "This step registers the 100-company 10-year SEC comment-letter raw cache as an official "
        "project artifact. The baseline uses the archived cache instead of redownloading SEC files."
    )

    if not summary_path.exists():
        st.warning("Step 2 artifacts are not available yet. Run `./.venv/bin/python run.py --step sec_raw`.")
    else:
        summary = load_json(summary_path)
        metrics = summary["metrics"]
        cols = st.columns(4)
        cols[0].metric("Tickers", metrics["ticker_count"])
        cols[1].metric("Threads", metrics["thread_count"])
        cols[2].metric("Filings", metrics["filing_count"])
        cols[3].metric("Raw cache MB", metrics["raw_cache_mb"])

        st.subheader("Processing Logic")
        st.markdown(
            """
- Copy the useful SEC raw cache from `Archive Prototype/data/raw/sec/` into official `data/raw/sec/`.
- Keep one shared raw cache that future samples can reuse.
- Scan metadata and extraction manifests instead of loading full raw documents into the app.
- Export lightweight preview and summary files for presentation.
"""
        )

        st.subheader("Output Files")
        st.dataframe(pd.DataFrame({"file": summary["output_files"]}), use_container_width=True)

        st.subheader("Raw Filing Preview")
        st.write("This preview shows filing-level rows from the extraction manifests.")
        st.dataframe(pd.read_csv(preview_path), use_container_width=True)

        st.subheader("Form Summary")
        st.dataframe(pd.read_csv(form_summary_path), use_container_width=True)

        with st.expander("Thread inventory preview"):
            st.dataframe(pd.read_csv(thread_inventory_path).head(100), use_container_width=True)

        with st.expander("QA notes"):
            for note in summary["notes"]:
                st.write(f"- {note}")


with tabs[3]:
    summary_path = WORKFLOW_DIR / "03_thread_dataset_summary.json"
    thread_preview_path = WORKFLOW_DIR / "03_thread_preview.csv"
    filing_preview_path = WORKFLOW_DIR / "03_thread_filing_preview.csv"
    role_summary_path = TABLES_DIR / "thread_role_summary.csv"
    full_thread_csv_path = DATA_DIR / "processed" / "thread_level.csv"
    full_thread_parquet_path = DATA_DIR / "processed" / "thread_level.parquet"

    st.header("Filing to Thread")
    st.write(
        "This step converts single SEC correspondence filings into one-row-per-thread records. "
        "A thread starts with a staff letter and keeps company responses and follow-up staff letters "
        "as context for the same regulatory review."
    )

    if not summary_path.exists():
        st.warning("Step 3 artifacts are not available yet. Run `./.venv/bin/python run.py --step threads`.")
    else:
        summary = load_json(summary_path)
        metrics = summary["metrics"]
        cols = st.columns(4)
        cols[0].metric("Thread tickers", metrics["ticker_count"])
        cols[1].metric("Threads", metrics["thread_count"])
        cols[2].metric("Filing rows", metrics["filing_count"])
        cols[3].metric("Median duration", f"{metrics['median_thread_duration_days']} days")

        st.subheader("Processing Logic")
        st.markdown(
            """
- Start from each `extraction_manifest.json` row as one SEC filing.
- Parse dates, forms, normalized roles, document paths, and extracted text.
- Group rows by `ticker` and `thread_id`.
- Use the first staff letter as the thread anchor; keep filer responses and staff actions as thread context.
- Export paired CSV/Parquet datasets for downstream event-level construction.
"""
        )

        st.subheader("Output Files")
        st.dataframe(pd.DataFrame({"file": summary["output_files"]}), use_container_width=True)

        st.subheader("Thread-Level Preview")
        st.write("Each row below is one SEC review thread created from one or more filing rows.")
        st.dataframe(pd.read_csv(thread_preview_path), use_container_width=True)

        st.subheader("Filing Role Summary")
        st.dataframe(pd.read_csv(role_summary_path), use_container_width=True)

        with st.expander("Filing-level manifest preview"):
            st.dataframe(pd.read_csv(filing_preview_path), use_container_width=True)

        with st.expander("Full thread table loaded by pandas"):
            st.write("The app loads the Parquet cache when available; the paired CSV remains available for manual inspection.")
            full_thread_df = read_table(full_thread_csv_path, full_thread_parquet_path)
            display_cols = [
                "ticker",
                "thread_id",
                "firm_name",
                "event_anchor_date",
                "n_filings_in_thread",
                "n_staff_letter",
                "n_filer_response",
                "thread_duration_days",
                "staff_letter_word_count",
                "text_status",
            ]
            st.dataframe(full_thread_df[display_cols].head(200), use_container_width=True)

        with st.expander("QA notes"):
            for note in summary["notes"]:
                st.write(f"- {note}")


with tabs[4]:
    summary_path = WORKFLOW_DIR / "04_event_dataset_summary.json"
    preview_path = WORKFLOW_DIR / "04_event_preview.csv"
    inclusion_summary_path = TABLES_DIR / "event_inclusion_summary.csv"
    full_event_csv_path = DATA_DIR / "processed" / "event_level_base.csv"
    full_event_parquet_path = DATA_DIR / "processed" / "event_level_base.parquet"

    st.header("Event Dataset")
    st.write(
        "This step turns one-row-per-thread records into event-study-ready observations. "
        "The event date is anchored on the first SEC staff letter in the thread."
    )

    if not summary_path.exists():
        st.warning("Step 4 artifacts are not available yet. Run `./.venv/bin/python run.py --step events`.")
    else:
        summary = load_json(summary_path)
        metrics = summary["metrics"]
        cols = st.columns(4)
        cols[0].metric("Raw events", metrics["raw_event_count"])
        cols[1].metric("Included events", metrics["included_event_count"])
        cols[2].metric("Excluded events", metrics["excluded_event_count"])
        cols[3].metric("Tickers", metrics["ticker_count"])

        st.subheader("Processing Logic")
        st.markdown(
            """
- Start from `thread_level` and `thread_filing_manifest`.
- Create a stable `event_id` from ticker plus the anchor staff-letter accession.
- Set `event_date` to the first SEC staff-letter date in the thread.
- Attach the anchor staff-letter URL and document metadata.
- Mark rows as included or excluded before topic/severity and market-data matching.
"""
        )

        st.subheader("Output Files")
        st.dataframe(pd.DataFrame({"file": summary["output_files"]}), use_container_width=True)

        st.subheader("Event Preview")
        st.write("Each row is one clean event observation that can be sent to topic/severity and market-return steps.")
        st.dataframe(pd.read_csv(preview_path), use_container_width=True)

        st.subheader("Inclusion Summary")
        st.dataframe(pd.read_csv(inclusion_summary_path), use_container_width=True)

        with st.expander("Full included event table loaded by pandas"):
            st.write("This is the analysis base before adding topic, severity, market returns, CAR windows, and regression fields.")
            full_event_df = read_table(full_event_csv_path, full_event_parquet_path)
            display_cols = [
                "event_id",
                "event_date",
                "ticker",
                "firm_name",
                "industry",
                "thread_id",
                "thread_round_count",
                "thread_duration_days",
                "staff_letter_word_count",
                "event_inclusion_status",
            ]
            st.dataframe(full_event_df[display_cols].head(200), use_container_width=True)

        with st.expander("QA notes"):
            for note in summary["notes"]:
                st.write(f"- {note}")


with tabs[5]:
    summary_path = WORKFLOW_DIR / "05_text_features_summary.json"
    preview_path = WORKFLOW_DIR / "05_text_features_preview.csv"
    topic_summary_path = TABLES_DIR / "topic_summary.csv"
    topic_detail_summary_path = TABLES_DIR / "topic_detail_summary.csv"
    severity_summary_path = TABLES_DIR / "severity_bucket_summary.csv"
    full_event_csv_path = DATA_DIR / "processed" / "event_level.csv"
    full_event_parquet_path = DATA_DIR / "processed" / "event_level.parquet"

    st.header("Text Features")
    st.write(
        "This step applies the V3 grouped rule-based topic classifier and computes severity features "
        "from staff-letter text and thread structure."
    )

    if not summary_path.exists():
        st.warning("Step 5 artifacts are not available yet. Run `./.venv/bin/python run.py --step text_features`.")
    else:
        summary = load_json(summary_path)
        metrics = summary["metrics"]
        cols = st.columns(4)
        cols[0].metric("Events", metrics["event_count"])
        cols[1].metric("Topic groups", metrics["topic_count"])
        cols[2].metric("Detail labels", metrics["topic_detail_count"])
        cols[3].metric("Severity buckets", metrics["severity_bucket_count"])

        st.subheader("Processing Logic")
        st.markdown(
            """
- Use staff-letter text as the primary classification text.
- Score regex patterns for substantive SEC issue areas.
- Keep `topic_detail` as the detailed audit label.
- Map `topic_detail` into six grouped `topic` labels for analysis and visualization.
- Compute `severity_score` from letter length, intensity terms, thread rounds, and amendment indicator.
"""
        )

        st.subheader("Output Files")
        st.dataframe(pd.DataFrame({"file": summary["output_files"]}), use_container_width=True)

        st.subheader("Text Feature Preview")
        st.dataframe(pd.read_csv(preview_path), use_container_width=True)

        st.subheader("Topic Summary")
        st.dataframe(pd.read_csv(topic_summary_path), use_container_width=True)

        st.subheader("Severity Buckets")
        st.dataframe(pd.read_csv(severity_summary_path), use_container_width=True)

        with st.expander("Topic detail mapping"):
            st.dataframe(pd.read_csv(topic_detail_summary_path), use_container_width=True)

        with st.expander("Full event table with text features loaded by pandas"):
            st.write("This is the event-level dataset after topic and severity are attached, before market data and CAR windows.")
            full_event_df = read_table(full_event_csv_path, full_event_parquet_path)
            display_cols = [
                "event_id",
                "event_date",
                "ticker",
                "topic",
                "topic_detail",
                "severity_score",
                "severity_bucket",
                "letter_word_count",
                "intensity_term_count",
                "thread_round_count",
                "amendment_indicator",
            ]
            st.dataframe(full_event_df[display_cols].head(200), use_container_width=True)

        with st.expander("QA notes"):
            for note in summary["notes"]:
                st.write(f"- {note}")


with tabs[6]:
    summary_path = WORKFLOW_DIR / "06_market_data_summary.json"
    preview_path = WORKFLOW_DIR / "06_market_data_preview.csv"
    coverage_path = TABLES_DIR / "market_coverage_summary.csv"
    full_market_csv_path = DATA_DIR / "processed" / "market_data.csv"
    full_market_parquet_path = DATA_DIR / "processed" / "market_data.parquet"

    st.header("Market Data")
    st.write(
        "This step prepares daily prices, volumes, and returns for event tickers plus the benchmark. "
        "These rows feed the later abnormal-return and CAR construction step."
    )

    if not summary_path.exists():
        st.warning("Step 6 artifacts are not available yet. Run `./.venv/bin/python run.py --step market`.")
    else:
        summary = load_json(summary_path)
        metrics = summary["metrics"]
        cols = st.columns(4)
        cols[0].metric("Rows", f"{metrics['row_count']:,}")
        cols[1].metric("Tickers", metrics["ticker_count"])
        cols[2].metric("Covered event tickers", metrics["event_ticker_covered_count"])
        cols[3].metric("Benchmark", metrics["benchmark_ticker"])

        st.subheader("Processing Logic")
        st.markdown(
            """
- Import the archived yfinance market-price cache into official `data/raw/market/`.
- Keep event tickers plus the configured benchmark ticker.
- Normalize date, ticker, close, volume, and return fields.
- Export a ticker-level coverage table before event-time matching.
- Leave abnormal returns and CAR windows for the next step.
"""
        )

        st.subheader("Output Files")
        st.dataframe(pd.DataFrame({"file": summary["output_files"]}), use_container_width=True)

        st.subheader("Market Data Preview")
        st.dataframe(pd.read_csv(preview_path), use_container_width=True)

        st.subheader("Ticker Coverage")
        st.dataframe(pd.read_csv(coverage_path), use_container_width=True)

        with st.expander("Full market table loaded by pandas"):
            st.write("The app loads the Parquet cache when available; the paired CSV remains available for manual inspection.")
            full_market_df = read_table(full_market_csv_path, full_market_parquet_path)
            st.dataframe(full_market_df.head(300), use_container_width=True)

        with st.expander("QA notes"):
            for note in summary["notes"]:
                st.write(f"- {note}")


with tabs[7]:
    summary_path = WORKFLOW_DIR / "07_event_study_regression_summary.json"
    event_time_preview_path = WORKFLOW_DIR / "07_event_time_preview.csv"
    regression_preview_path = WORKFLOW_DIR / "07_regression_dataset_preview.csv"
    qa_summary_path = TABLES_DIR / "event_time_qa_summary.csv"
    average_car_path = TABLES_DIR / "average_car.csv"
    topic_average_car_path = TABLES_DIR / "topic_average_car.csv"
    topic_car_summary_path = TABLES_DIR / "topic_car_summary.csv"
    baseline_regression_path = TABLES_DIR / "baseline_regression.csv"

    st.header("Event Study & Regression")
    st.write(
        "This step converts market returns into event-time abnormal returns, CAR windows, "
        "regression-ready rows, and baseline regression tables."
    )

    if not summary_path.exists():
        st.warning("Step 7 artifacts are not available yet. Run `./.venv/bin/python run.py --step event_study`.")
    else:
        summary = load_json(summary_path)
        metrics = summary["metrics"]
        cols = st.columns(4)
        cols[0].metric("Event-time rows", f"{metrics['event_time_row_count']:,}")
        cols[1].metric("Events matched", metrics["event_time_event_count"])
        cols[2].metric("Regression rows", metrics["regression_row_count"])
        cols[3].metric("Included rows", metrics["regression_included_count"])

        st.subheader("Processing Logic")
        st.markdown(
            """
- Match each SEC event to the next available trading day.
- Build event-time rows over the configured window.
- Compute abnormal return as stock return minus benchmark return.
- Sum abnormal returns into CAR windows: `CAR_-3_-1`, `CAR_-1_3`, and `CAR_1_60`.
- Run baseline OLS specifications using topic, severity score, and pre-event volatility.
"""
        )

        st.subheader("Output Files")
        st.dataframe(pd.DataFrame({"file": summary["output_files"]}), use_container_width=True)

        st.subheader("Event-Time Preview")
        st.dataframe(pd.read_csv(event_time_preview_path), use_container_width=True)

        st.subheader("Event-Time QA")
        st.dataframe(pd.read_csv(qa_summary_path), use_container_width=True)

        st.subheader("Regression Dataset Preview")
        st.dataframe(pd.read_csv(regression_preview_path), use_container_width=True)

        st.subheader("Topic CAR Summary")
        st.dataframe(pd.read_csv(topic_car_summary_path), use_container_width=True)

        with st.expander("Average CAR table"):
            st.dataframe(pd.read_csv(average_car_path), use_container_width=True)

        with st.expander("Topic-average CAR table"):
            st.dataframe(pd.read_csv(topic_average_car_path), use_container_width=True)

        with st.expander("Baseline regression table"):
            st.dataframe(pd.read_csv(baseline_regression_path), use_container_width=True)

        with st.expander("QA notes"):
            for note in summary["notes"]:
                st.write(f"- {note}")


with tabs[8]:
    st.header("Full Code Example")
    st.write("The official pipeline is orchestrated from the project root.")
    st.code(
        "./.venv/bin/python run.py --step sp500 --refresh\n"
        "./.venv/bin/python run.py --step sec_raw\n"
        "./.venv/bin/python run.py --step threads\n"
        "./.venv/bin/python run.py --step events\n"
        "./.venv/bin/python run.py --step text_features\n"
        "./.venv/bin/python run.py --step market\n"
        "./.venv/bin/python run.py --step event_study",
        language="bash",
    )
    st.write("The pattern will extend as more numbered modules are extracted.")
